import { Tool } from "@/types";

const toneField = {
  name: "tone",
  label: "Tone",
  type: "select" as const,
  options: [
    "Professional",
    "Friendly",
    "Bold",
    "Luxury",
    "Playful",
    "Minimal",
    "Persuasive",
    "Witty",
  ],
};

const languageField = {
  name: "language",
  label: "Language",
  type: "select" as const,
  options: ["English", "Spanish", "French", "German", "Portuguese", "Hindi"],
};

const lengthField = {
  name: "length",
  label: "Length",
  type: "select" as const,
  options: ["Short", "Medium", "Long"],
};

const keywordsField = {
  name: "keywords",
  label: "Keywords",
  type: "keywords" as const,
  placeholder: "Add keywords separated by commas",
};

const instructionsField = {
  name: "instructions",
  label: "Additional instructions",
  type: "textarea" as const,
  placeholder: "Anything else the AI should know…",
};

function baseFields(topicLabel = "Topic", topicPlaceholder = "e.g. Benefits of remote work for small teams") {
  return [
    {
      name: "topic",
      label: topicLabel,
      type: "text" as const,
      placeholder: topicPlaceholder,
      required: true,
    },
    toneField,
    languageField,
    lengthField,
    keywordsField,
    instructionsField,
  ];
}

export const tools: Tool[] = [
  // Writing
  {
    slug: "ai-blog-writer",
    name: "AI Blog Writer",
    description: "Generate full-length, structured blog posts from a single topic.",
    category: "Writing",
    icon: "PenLine",
    credits: 15,
    fields: baseFields(),
  },
  {
    slug: "article-writer",
    name: "Article Writer",
    description: "Draft well-researched articles with clear sections and flow.",
    category: "Writing",
    icon: "FileText",
    credits: 15,
    fields: baseFields(),
  },
  {
    slug: "email-writer",
    name: "Email Writer",
    description: "Write clear, on-brand emails for any occasion in seconds.",
    category: "Writing",
    icon: "Mail",
    credits: 5,
    fields: baseFields("Email purpose", "e.g. Follow up after a product demo"),
  },
  {
    slug: "story-generator",
    name: "Story Generator",
    description: "Turn a premise into a short story with characters and arc.",
    category: "Writing",
    icon: "BookOpen",
    credits: 10,
    fields: baseFields("Story premise", "e.g. A lighthouse keeper who finds a message in a bottle"),
  },
  {
    slug: "product-description",
    name: "Product Description",
    description: "Craft persuasive, conversion-focused product descriptions.",
    category: "Writing",
    icon: "Package",
    credits: 5,
    fields: baseFields("Product name & details", "e.g. Ceramic pour-over coffee dripper, minimalist design"),
  },
  {
    slug: "ad-copy-generator",
    name: "Ad Copy Generator",
    description: "Generate high-converting ad copy for any platform.",
    category: "Writing",
    icon: "Megaphone",
    credits: 5,
    fields: baseFields("What are you advertising?"),
  },
  {
    slug: "cover-letter-writer",
    name: "Cover Letter Writer",
    description: "Generate a tailored, professional cover letter.",
    category: "Writing",
    icon: "FileSignature",
    credits: 5,
    fields: baseFields("Role & company", "e.g. Product Designer at a fintech startup"),
  },
  {
    slug: "paraphrasing-tool",
    name: "Paraphrasing Tool",
    description: "Rewrite text while keeping the original meaning intact.",
    category: "Writing",
    icon: "Repeat",
    credits: 5,
    fields: baseFields("Text to paraphrase"),
  },
  {
    slug: "grammar-fixer",
    name: "Grammar Fixer",
    description: "Fix grammar, spelling, and punctuation instantly.",
    category: "Writing",
    icon: "SpellCheck",
    credits: 3,
    fields: baseFields("Text to fix"),
  },
  {
    slug: "essay-writer",
    name: "Essay Writer",
    description: "Generate structured essays with intro, body, and conclusion.",
    category: "Writing",
    icon: "GraduationCap",
    credits: 15,
    fields: baseFields("Essay topic"),
  },
  // SEO
  {
    slug: "seo-article-writer",
    name: "SEO Article Writer",
    description: "Write long-form, keyword-optimized SEO articles that rank.",
    category: "SEO",
    icon: "TrendingUp",
    credits: 20,
    fields: baseFields(),
  },
  {
    slug: "keyword-cluster",
    name: "Keyword Cluster",
    description: "Group related keywords into content-ready clusters.",
    category: "SEO",
    icon: "Layers",
    credits: 10,
    fields: baseFields("Seed keyword"),
  },
  {
    slug: "search-intent-analyzer",
    name: "Search Intent Analyzer",
    description: "Understand what searchers actually want for a query.",
    category: "SEO",
    icon: "Search",
    credits: 8,
    fields: baseFields("Search query"),
  },
  {
    slug: "meta-title-generator",
    name: "Meta Title Generator",
    description: "Generate click-worthy, SEO-friendly meta titles.",
    category: "SEO",
    icon: "Heading",
    credits: 3,
    fields: baseFields("Page topic"),
  },
  {
    slug: "meta-description-generator",
    name: "Meta Description Generator",
    description: "Write compelling meta descriptions that boost CTR.",
    category: "SEO",
    icon: "AlignLeft",
    credits: 3,
    fields: baseFields("Page topic"),
  },
  {
    slug: "faq-generator",
    name: "FAQ Generator",
    description: "Generate a relevant FAQ section for any topic or product.",
    category: "SEO",
    icon: "HelpCircle",
    credits: 8,
    fields: baseFields(),
  },
  {
    slug: "content-brief-generator",
    name: "Content Brief Generator",
    description: "Create a full content brief to guide writers or AI.",
    category: "SEO",
    icon: "ClipboardList",
    credits: 10,
    fields: baseFields("Target keyword"),
  },
  {
    slug: "internal-link-finder",
    name: "Internal Links",
    description: "Suggest smart internal linking opportunities for an article.",
    category: "SEO",
    icon: "Link2",
    credits: 8,
    fields: baseFields("Article topic"),
  },
  {
    slug: "schema-generator",
    name: "Schema Generator",
    description: "Generate structured data / schema markup suggestions.",
    category: "SEO",
    icon: "Braces",
    credits: 8,
    fields: baseFields("Page type & topic"),
  },
  // Marketing
  {
    slug: "landing-page-copy",
    name: "Landing Page Copy",
    description: "Generate persuasive copy for high-converting landing pages.",
    category: "Marketing",
    icon: "LayoutTemplate",
    credits: 15,
    fields: baseFields("Product / offer"),
  },
  {
    slug: "value-proposition-generator",
    name: "Value Proposition Generator",
    description: "Craft a sharp, differentiated value proposition.",
    category: "Marketing",
    icon: "Sparkles",
    credits: 8,
    fields: baseFields("Product / business"),
  },
  {
    slug: "press-release-writer",
    name: "Press Release Writer",
    description: "Draft a newsworthy, professionally formatted press release.",
    category: "Marketing",
    icon: "Newspaper",
    credits: 15,
    fields: baseFields("Announcement"),
  },
  {
    slug: "brand-name-generator",
    name: "Brand Name Generator",
    description: "Generate original brand name ideas for your business.",
    category: "Marketing",
    icon: "Tag",
    credits: 5,
    fields: baseFields("Describe your business"),
  },
  {
    slug: "slogan-generator",
    name: "Slogan Generator",
    description: "Generate catchy taglines and slogans.",
    category: "Marketing",
    icon: "Quote",
    credits: 5,
    fields: baseFields("Brand / product"),
  },
  // Social Media
  {
    slug: "instagram-caption",
    name: "Instagram Caption",
    description: "Generate scroll-stopping Instagram captions with hashtags.",
    category: "Social Media",
    icon: "Instagram",
    credits: 5,
    fields: baseFields("Post topic"),
  },
  {
    slug: "linkedin-post-writer",
    name: "LinkedIn Post Writer",
    description: "Write thoughtful, engagement-driving LinkedIn posts.",
    category: "Social Media",
    icon: "Linkedin",
    credits: 5,
    fields: baseFields("Post topic"),
  },
  {
    slug: "tweet-generator",
    name: "X / Tweet Generator",
    description: "Generate punchy posts and threads for X.",
    category: "Social Media",
    icon: "Twitter",
    credits: 3,
    fields: baseFields("Topic"),
  },
  {
    slug: "facebook-ad-copy",
    name: "Facebook Ad Copy",
    description: "Generate Facebook ad copy tuned for conversions.",
    category: "Social Media",
    icon: "Facebook",
    credits: 5,
    fields: baseFields("What are you promoting?"),
  },
  {
    slug: "hashtag-generator",
    name: "Hashtag Generator",
    description: "Generate relevant, trending hashtags for any post.",
    category: "Social Media",
    icon: "Hash",
    credits: 3,
    fields: baseFields("Post topic"),
  },
  {
    slug: "social-media-bio",
    name: "Social Media Bio",
    description: "Write a punchy bio for any social platform.",
    category: "Social Media",
    icon: "IdCard",
    credits: 3,
    fields: baseFields("About you / your brand"),
  },
  // YouTube
  {
    slug: "youtube-script-writer",
    name: "YouTube Script Writer",
    description: "Generate a full video script with hook, body, and CTA.",
    category: "YouTube",
    icon: "Clapperboard",
    credits: 15,
    fields: baseFields("Video topic"),
  },
  {
    slug: "youtube-title-generator",
    name: "YouTube Title Generator",
    description: "Generate high-CTR YouTube titles.",
    category: "YouTube",
    icon: "Youtube",
    credits: 3,
    fields: baseFields("Video topic"),
  },
  {
    slug: "youtube-description-generator",
    name: "YouTube Description Generator",
    description: "Write an SEO-friendly YouTube video description.",
    category: "YouTube",
    icon: "MonitorPlay",
    credits: 5,
    fields: baseFields("Video topic"),
  },
  {
    slug: "video-hook-generator",
    name: "Video Hook Generator",
    description: "Generate scroll-stopping opening hooks for short-form video.",
    category: "YouTube",
    icon: "Zap",
    credits: 3,
    fields: baseFields("Video topic"),
  },
  // Images
  {
    slug: "ai-image-prompt-generator",
    name: "Image Prompt Generator",
    description: "Turn a simple idea into a detailed AI image prompt.",
    category: "Images",
    icon: "ImagePlus",
    credits: 3,
    fields: baseFields("Describe the image you want"),
  },
  {
    slug: "logo-concept-generator",
    name: "Logo Concept Generator",
    description: "Generate logo concept directions and prompts for a brand.",
    category: "Images",
    icon: "Shapes",
    credits: 5,
    fields: baseFields("Brand name & vibe"),
  },
  {
    slug: "thumbnail-concept-generator",
    name: "Thumbnail Concept Generator",
    description: "Generate high-CTR thumbnail concepts for video content.",
    category: "Images",
    icon: "Image",
    credits: 5,
    fields: baseFields("Video topic"),
  },
  // Video
  {
    slug: "video-prompt-generator",
    name: "Video Prompt Generator",
    description: "Turn an idea into a structured AI video generation prompt.",
    category: "Video",
    icon: "Film",
    credits: 5,
    fields: baseFields("Describe the video you want"),
  },
  {
    slug: "video-storyboard-generator",
    name: "Storyboard Generator",
    description: "Break a concept into a scene-by-scene storyboard.",
    category: "Video",
    icon: "GalleryHorizontal",
    credits: 10,
    fields: baseFields("Video concept"),
  },
  // Business
  {
    slug: "business-plan-generator",
    name: "Business Plan Generator",
    description: "Generate a structured business plan outline.",
    category: "Business",
    icon: "Briefcase",
    credits: 20,
    fields: baseFields("Business idea"),
  },
  {
    slug: "swot-analysis-generator",
    name: "SWOT Analysis Generator",
    description: "Generate a SWOT analysis for your business or idea.",
    category: "Business",
    icon: "Grid2x2",
    credits: 10,
    fields: baseFields("Business / product"),
  },
  {
    slug: "job-description-writer",
    name: "Job Description Writer",
    description: "Write a clear, compelling job description.",
    category: "Business",
    icon: "Users",
    credits: 8,
    fields: baseFields("Role title"),
  },
  {
    slug: "website-copy-generator",
    name: "Website Copy Generator",
    description: "Generate homepage and landing copy for your website.",
    category: "Business",
    icon: "Globe",
    credits: 15,
    fields: baseFields("What does your business do?"),
  },
  // Coding
  {
    slug: "code-generator",
    name: "Code Generator",
    description: "Generate code snippets from a plain-language description.",
    category: "Coding",
    icon: "Code2",
    credits: 8,
    fields: baseFields("Describe what the code should do"),
  },
  {
    slug: "code-explainer",
    name: "Code Explainer",
    description: "Explain what a piece of code does in plain English.",
    category: "Coding",
    icon: "Terminal",
    credits: 5,
    fields: baseFields("Paste code or describe it"),
  },
  {
    slug: "regex-generator",
    name: "Regex Generator",
    description: "Generate a regular expression from a plain description.",
    category: "Coding",
    icon: "Binary",
    credits: 3,
    fields: baseFields("Describe the pattern you need"),
  },
];

export const categories: (Tool["category"] | "All")[] = [
  "All",
  "Writing",
  "SEO",
  "Marketing",
  "Social Media",
  "YouTube",
  "Images",
  "Video",
  "Business",
  "Coding",
];

export function getToolBySlug(slug: string) {
  return tools.find((t) => t.slug === slug);
}
